// ─── Field name maps: JS camelCase ↔ DB snake_case ───────────────────────────

export const providerToDb = (p) => ({
  id: p.id,
  fname: p.fname,
  lname: p.lname,
  cred: p.cred,
  spec: p.spec,
  status: p.status,
  email: p.email,
  phone: p.phone,
  focus: p.focus,
  taxonomy_code: p.taxonomyCode || null,
  taxonomy_desc: p.taxonomyDesc || null,
  npi: p.npi,
  caqh: p.caqh,
  caqh_attest: p.caqhAttest || null,
  caqh_due: p.caqhDue || null,
  medicaid: p.medicaid,
  ptan: p.ptan,
  license: p.license,
  license_exp: p.licenseExp || null,
  mal_carrier: p.malCarrier,
  mal_policy: p.malPolicy,
  mal_exp: p.malExp || null,
  dea: p.dea,
  dea_exp: p.deaExp || null,
  recred: p.recred || null,
  supervisor: p.supervisor,
  sup_exp: p.supExp || null,
  notes: p.notes,
  avatar_url: p.avatarUrl || null,
  pt_url: p.ptUrl || null,
  pt_status: p.ptStatus || null,
  pt_monthly_fee: p.ptMonthlyFee || false,
  pt_notes: p.ptNotes || null,
})

export const providerFromDb = (p) => ({
  id: p.id,
  fname: p.fname || '',
  lname: p.lname || '',
  cred: p.cred || '',
  spec: p.spec || '',
  status: p.status || 'Active',
  email: p.email || '',
  phone: p.phone || '',
  focus: p.focus || '',
  taxonomyCode: p.taxonomy_code || '',
  taxonomyDesc: p.taxonomy_desc || '',
  npi: p.npi || '',
  caqh: p.caqh || '',
  caqhAttest: p.caqh_attest || '',
  caqhDue: p.caqh_due || '',
  medicaid: p.medicaid || '',
  ptan: p.ptan || '',
  license: p.license || '',
  licenseExp: p.license_exp || '',
  malCarrier: p.mal_carrier || '',
  malPolicy: p.mal_policy || '',
  malExp: p.mal_exp || '',
  dea: p.dea || '',
  deaExp: p.dea_exp || '',
  recred: p.recred || '',
  supervisor: p.supervisor || '',
  supExp: p.sup_exp || '',
  notes: p.notes || '',
  avatarUrl: p.avatar_url || '',
  ptUrl: p.pt_url || '',
  ptStatus: p.pt_status || 'None',
  ptMonthlyFee: p.pt_monthly_fee || false,
  ptNotes: p.pt_notes || '',
})

export const enrollmentToDb = (e) => ({
  id: e.id,
  prov_id: e.provId || null,
  pay_id: e.payId || null,
  stage: e.stage,
  submitted: e.submitted || null,
  effective: e.effective || null,
  recred: e.recred || null,
  eft: e.eft,
  era: e.era,
  followup: e.followup || null,
  contract: e.contract,
  notes: e.notes,
})

export const enrollmentFromDb = (e) => ({
  id: e.id,
  provId: e.prov_id || '',
  payId: e.pay_id || '',
  stage: e.stage || 'Not Started',
  submitted: e.submitted || '',
  effective: e.effective || '',
  recred: e.recred || '',
  eft: e.eft || 'Not Set Up',
  era: e.era || 'Not Set Up',
  followup: e.followup || '',
  contract: e.contract || 'No',
  notes: e.notes || '',
})

export const payerToDb = (p) => ({
  id: p.id,
  name: p.name,
  payer_id: p.payerId,
  type: p.type,
  phone: p.phone,
  email: p.email,
  portal: p.portal,
  timeline: p.timeline,
  notes: p.notes,
})

export const payerFromDb = (p) => ({
  id: p.id,
  name: p.name || '',
  payerId: p.payer_id || '',
  type: p.type || 'Commercial',
  phone: p.phone || '',
  email: p.email || '',
  portal: p.portal || '',
  timeline: p.timeline || '60–90 days',
  notes: p.notes || '',
})

export const documentToDb = (d) => ({
  id: d.id,
  prov_id: d.provId || null,
  type: d.type,
  issuer: d.issuer,
  number: d.number,
  issue: d.issue || null,
  exp: d.exp || null,
  notes: d.notes,
})

export const documentFromDb = (d) => ({
  id: d.id,
  provId: d.prov_id || '',
  type: d.type || '',
  issuer: d.issuer || '',
  number: d.number || '',
  issue: d.issue || '',
  exp: d.exp || '',
  notes: d.notes || '',
})

export const taskToDb = (t) => ({
  id: t.id,
  task: t.task,
  due: t.due || null,
  priority: t.priority,
  status: t.status,
  cat: t.cat,
  prov_id: t.provId || null,
  pay_id: t.payId || null,
  notes: t.notes,
})

export const taskFromDb = (t) => ({
  id: t.id,
  task: t.task || '',
  due: t.due || '',
  priority: t.priority || 'Medium',
  status: t.status || 'Open',
  cat: t.cat || 'Follow-up',
  provId: t.prov_id || '',
  payId: t.pay_id || '',
  notes: t.notes || '',
})

export const auditFromDb = (a) => ({
  id: a.id,
  ts: a.ts,
  type: a.type || '',
  action: a.action || '',
  detail: a.detail || '',
  entity: a.entity || '',
})

export const settingsFromDb = (s) => ({
  practice: s.practice || 'Positive Inner Self, LLC',
  address: s.address || '6700 SW 105th Ave Suite 215, Beaverton, OR 97008',
  phone: s.phone || '(503) 468-4791',
  email: s.email || 'intake@positiveinnerself.com',
  alertDays: s.alert_days || 90,
  caqhDays: s.caqh_days || 30,
})
